##' rbindlist with names
##' 
##' This function implements \code{rbindlist} but adds an optional argument,
##' \code{names}, which allows us to keep the names of each
##' sub-list which we \code{rbindlist}-ify.
##' 
##' @param l A list of \code{data.frame}s, \code{data.table}s or 
##'   \code{data.frame} shaped \code{list}s.
##' @param names If \code{names} is:
##' \itemize{
##' \item{\code{FALSE}: Do not generate a vector of names.}
##' \item{\code{TRUE}: Generate a vector of names called \code{.Names}, and
##'   append it to the \code{data.table} generated by \code{rbindlist}.}
##' \item{A string: Generate a vector of names called \code{names}, and
##'   append it to the \code{data.table} generated by \code{rbindlist}.}
##' }
##' @export
rbindlistn <- function(l, names=FALSE) {
  
  if (identical(names, FALSE)) {
    return(rbindlist(l))
  }  
  
  if (identical(names, TRUE)) {
    names <- ".Names"
  }
  
  output <- rbindlist(l)
  nm <- names(l)
  if (is.null(nm)) {
    warning("The 'names' attribute of your list is NULL")
    nm <- paste0("V", 1:length(l))
  }
  
  if (any(nm == '')) {
    warning("Some elements in your list are unnamed")
    nm[nm == ''] <- paste0("V", 1:length(l))[nm == '']
  }
  output[, eval(names) := rep(nm, sapply(l, nrow, USE.NAMES=FALSE))]
  return(output)
}
